AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template: S3 Bucket'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'cf-demo-bucket-${AWS::AccountId}'
      Tags:
        - Key: Environment
          Value: Dev
        - Key: yor_trace
          Value: e712e53a-d146-422c-b417-653e30c99756
        - Key: yor_name
          Value: S3Bucket
