name: Placeholder Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Repository is being reset. Add new IaC files to trigger deployments."
